version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nikhil
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - /home/ubuntu/wanderlust/backend/volume:/data/db
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    image: nikhildhakad/backend-wanderlust:v2.18
    env_file:
      - ./backend/.env.docker
    volumes:
      - /home/ubuntu/wanderlust/backend/back-data:/app/public
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    image: nikhildhakad/frontend-wanderlust:v2.18
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
    depends_on:
      - mongodb
